[package]
name = "changes"
version = "0.1.0"
authors = ["Coleman McFarland <coleman.mcfarland@gmail.com>"]

[dependencies]
libloading = "0.5"
maud = { git = "https://github.com/lfairy/maud.git", branch = "master", features = ["rocket"] }
rocket = "*"
rocket_codegen = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
reqwest = "0.8.5"
url = "1.2"
rand = "0.4"
